version: "3.9"

services:
  fastapi_app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
    - PYTHONPATH=/app  # Add root folder to PYTHONPATH
